#!/usr/bin/env python3
"""Simple web server to share audio files with phone"""

import http.server
import socketserver
import os
from pathlib import Path

class AudioFileHandler(http.server.SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', '*')
        super().end_headers()

def serve_audio_files():
    """Start a simple web server to share audio files"""
    PORT = 8080
    
    # Create an index page
    html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>GhostVoiceGPT Audio Files</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; }
        .audio-item { margin: 20px 0; padding: 15px; border: 1px solid #ddd; border-radius: 5px; }
        audio { width: 100%; margin: 10px 0; }
        .download { background: #007cba; color: white; padding: 8px 16px; text-decoration: none; border-radius: 3px; }
        h1 { color: #333; text-align: center; }
        .persona { font-weight: bold; color: #666; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🎤 GhostVoiceGPT Voice Samples</h1>
        
        <div class="audio-item">
            <div class="persona">Stephen - Confident & Knowledgeable</div>
            <audio controls><source src="demo_stephen.mp3" type="audio/mpeg"></audio>
            <a href="demo_stephen.mp3" class="download" download>Download</a>
        </div>
        
        <div class="audio-item">
            <div class="persona">Nova - Warm & Empathetic</div>
            <audio controls><source src="demo_nova.mp3" type="audio/mpeg"></audio>
            <a href="demo_nova.mp3" class="download" download>Download</a>
        </div>
        
        <div class="audio-item">
            <div class="persona">Sugar - Bubbly & Energetic</div>
            <audio controls><source src="demo_sugar.mp3" type="audio/mpeg"></audio>
            <a href="demo_sugar.mp3" class="download" download>Download</a>
        </div>
        
        <div class="audio-item">
            <div class="persona">Quick Test</div>
            <audio controls><source src="quick_test.mp3" type="audio/mpeg"></audio>
            <a href="quick_test.mp3" class="download" download>Download</a>
        </div>
        
        <p style="text-align: center; margin-top: 30px; color: #666;">
            Generated by GhostVoiceGPT using ElevenLabs voices
        </p>
    </div>
</body>
</html>
"""
    
    # Write the index file
    with open('index.html', 'w') as f:
        f.write(html_content)
    
    # Start server
    with socketserver.TCPServer(("", PORT), AudioFileHandler) as httpd:
        print(f"🌐 Audio server running at:")
        print(f"   Local: http://localhost:{PORT}")
        print(f"   Network: http://[YOUR_PC_IP]:{PORT}")
        print(f"\n📱 On your phone:")
        print(f"   1. Connect to same WiFi as this PC")
        print(f"   2. Find your PC's IP address")
        print(f"   3. Open browser and go to http://[PC_IP]:{PORT}")
        print(f"\n⏹️  Press Ctrl+C to stop server")
        
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print(f"\n🛑 Server stopped")

if __name__ == "__main__":
    serve_audio_files()